name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build AppImage
      run: |
        npm install -g electron-builder
        npm run build
    
    - name: Upload AppImage
      uses: actions/upload-artifact@v3
      with:
        name: Linux-Clipboard-Manager
        path: dist/*.AppImage
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*.AppImage
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 